### 1. Importar librerías y paquetes

In [1]:
# Importar librerias
import pandas as pd
import unicodedata
import os

### 2. Importar datos de origen

#### 2.1. Importar datos de Provincias

In [2]:
# Importar datos de Provincias (del INE)
df_provincias = pd.read_excel(
    "../Data/Raw/Public/INE/D_provincias_ine_prev.xlsx"
)

# Visualizar los resultados
df_provincias.head(5)

  id_provincia  cod-ca  cod-prv nombre_provincia nombre_provincia_completo
0        01-04       1        4          Almería           01-04 - Almería
1        01-11       1       11            Cádiz             01-11 - Cádiz
2        01-14       1       14          Córdoba           01-14 - Córdoba
3        01-18       1       18          Granada           01-18 - Granada
4        01-21       1       21           Huelva            01-21 - Huelva

#### 2.2. Importar datos de CCAA

In [3]:
# Importar datos de CCAA (del INE)
df_ccaa = pd.read_excel(
    "../Data/Raw/Public/INE/D_ccaa_ine_prev.xlsx"
)

# Visualizar los resultados
df_ccaa.head(5)

   id     nombre nombre_completo
0   1  Andalucía    01 Andalucía
1   2     Aragón       02 Aragón
2   3   Asturias     03 Asturias
3   4    Balears      04 Balears
4   5   Canarias     05 Canarias

### 3. Transformación de datos (tablas dimensiones)

#### 3.1 Tabla Dimensiones Provincias

In [4]:
# Sacar tildes del campo nombre_provincia
df_provincias["nombre_provincia_st"] = df_provincias["nombre_provincia"].apply(
    lambda x: ''.join(
        c for c in unicodedata.normalize('NFD', x)
        if unicodedata.category(c) != 'Mn'
    )
)

# Renombrar columnas
df_provincias = df_provincias.rename(columns={
    "id_provincia": "Id_provincia",
    "cod-ca": "Id_ccaa",
    "cod-prv": "Cod-prv",
    "nombre_provincia": "Nombre_provincia",
    "nombre_provincia_st": "Nombre_provincia_st",
    "nombre_provincia_completo": "Nombre_provincia_completo"    
})

# Ordenar las columnas
df_provincias = df_provincias[['Id_provincia', 'Id_ccaa', 'Cod-prv', 'Nombre_provincia', 'Nombre_provincia_st',
       'Nombre_provincia_completo']]

# Visualizar los resultados
df_provincias

,Id_provincia,Id_ccaa,Cod-prv,Nombre_provincia,Nombre_provincia_st,Nombre_provincia_completo
0,01-04,1,4,Almería,Almeria,01-04 - Almería
1,01-11,1,11,Cádiz,Cadiz,01-11 - Cádiz
2,01-14,1,14,Córdoba,Cordoba,01-14 - Córdoba
3,01-18,1,18,Granada,Granada,01-18 - Granada
4,01-21,1,21,Huelva,Huelva,01-21 - Huelva
5,01-23,1,23,Jaén,Jaen,01-23 - Jaén
6,01-29,1,29,Málaga,Malaga,01-29 - Málaga
7,01-41,1,41,Sevilla,Sevilla,01-41 - Sevilla
8,02-22,2,22,Huesca,Huesca,02-22 - Huesca
9,02-44,2,44,Teruel,Teruel,02-44 - Teruel
10,02-50,2,50,Zaragoza,Zaragoza,02-50 - Zaragoza
11,03-33,3,33,Asturias,Asturias,03-33 - Asturias
12,04-07,4,7,Illes Balears,Illes Balears,04-07 - Illes Balears
13,05-35,5,35,Las Palmas,Las Palmas,05-35 - Las Palmas
14,05-38,5,38,Santa Cruz de Tenerife,Santa Cruz de Tenerife,05-38 - Santa Cruz de Tenerife
15,06-39,6,39,Cantabria,Cantabria,06-39 - Cantabria
16,07-05,7,5,Ávila,Avila,07-05 - Ávila
17,07-09,7,9,Burgos,Burgos,07-09 - Burgos
18,07-24,7,24,León,Leon,07-24 - León
19,07-34,7,34,Palencia,Palencia,07-34 - Palencia
20,07-37,7,37,Salamanca,Salamanca,07-37 - Salamanca
21,07-40,7,40,Segovia,Segovia,07-40 - Segovia
22,07-42,7,42,Soria,Soria,07-42 - Soria
23,07-47,7,47,Valladolid,Valladolid,07-47 - Valladolid
24,07-49,7,49,Zamora,Zamora,07-49 - Zamora
25,08-02,8,2,Albacete,Albacete,08-02 - Albacete
26,08-13,8,13,Ciudad Real,Ciudad Real,08-13 - Ciudad Real
27,08-16,8,16,Cuenca,Cuenca,08-16 - Cuenca
28,08-19,8,19,Guadalajara,Guadalajara,08-19 - Guadalajara
29,08-45,8,45,Toledo,Toledo,08-45 - Toledo
30,09-08,9,8,Barcelona,Barcelona,09-08 - Barcelona
31,09-17,9,17,Girona,Girona,09-17 - Girona
32,09-25,9,25,Lleida,Lleida,09-25 - Lleida
33,09-43,9,43,Tarragona,Tarragona,09-43 - Tarragona
34,10-03,10,3,Alicante / Alacant,Alicante / Alacant,10-03 - Alicante / Alacant
35,10-12,10,12,Castellón / Castelló,Castellon / Castello,10-12 - Castellón / Castelló
36,10-46,10,46,Valencia / València,Valencia / Valencia,10-46 - Valencia / València
37,11-06,11,6,Badajoz,Badajoz,11-06 - Badajoz
38,11-10,11,10,Cáceres,Caceres,11-10 - Cáceres
39,12-15,12,15,A Coruña,A Coruna,12-15 - A Coruña
40,12-27,12,27,Lugo,Lugo,12-27 - Lugo
41,12-32,12,32,Ourense,Ourense,12-32 - Ourense
42,12-36,12,36,Pontevedra,Pontevedra,12-36 - Pontevedra
43,13-28,13,28,Madrid,Madrid,13-28 - Madrid
44,14-30,14,30,Murcia,Murcia,14-30 - Murcia
45,15-31,15,31,Navarra,Navarra,15-31 - Navarra
46,16-01,16,1,Araba / Álava,Araba / Alava,16-01 - Araba / Álava
47,16-20,16,20,Gipuzkoa,Gipuzkoa,16-20 - Gipuzkoa
48,16-48,16,48,Bizkaia,Bizkaia,16-48 - Bizkaia
49,17-26,17,26,La Rioja,La Rioja,17-26 - La Rioja
50,18-51,18,51,Ceuta,Ceuta,18-51 - Ceuta
51,19-52,19,52,Melilla,Melilla,19-52 - Melilla

#### 3.2 Tabla Dimensiones CCAA

In [5]:
# Renombrar columnas
df_ccaa = df_ccaa.rename(columns={
    "id": "Id_ccaa",
    "nombre": "Nombre_ccaa",
    "nombre_completo": "Nombre_ccaa_completo" 
})

# Visualizar los resultados
df_ccaa.head(5)

   Id_ccaa Nombre_ccaa Nombre_ccaa_completo
0        1   Andalucía         01 Andalucía
1        2      Aragón            02 Aragón
2        3    Asturias          03 Asturias
3        4     Balears           04 Balears
4        5    Canarias          05 Canarias

#### 3.3 Tabla Dimensiones Geografía

In [6]:
#Join DFs (provincia y ccaa)
df_geografia = df_provincias.merge(
    df_ccaa[
        ["Id_ccaa","Nombre_ccaa","Nombre_ccaa_completo"]
    ],
    how="left",
    left_on="Id_ccaa",
    right_on="Id_ccaa"
)

#Reordenar columnas del DF
df_geografia = df_geografia[['Id_provincia', 'Cod-prv', 'Nombre_provincia',
       'Nombre_provincia_st', 'Nombre_provincia_completo', 'Id_ccaa','Nombre_ccaa','Nombre_ccaa_completo']]

#Visualizar los resultados
df_geografia

,Id_provincia,Cod-prv,Nombre_provincia,Nombre_provincia_st,Nombre_provincia_completo,Id_ccaa,Nombre_ccaa,Nombre_ccaa_completo
0,01-04,4,Almería,Almeria,01-04 - Almería,1,Andalucía,01 Andalucía
1,01-11,11,Cádiz,Cadiz,01-11 - Cádiz,1,Andalucía,01 Andalucía
2,01-14,14,Córdoba,Cordoba,01-14 - Córdoba,1,Andalucía,01 Andalucía
3,01-18,18,Granada,Granada,01-18 - Granada,1,Andalucía,01 Andalucía
4,01-21,21,Huelva,Huelva,01-21 - Huelva,1,Andalucía,01 Andalucía
5,01-23,23,Jaén,Jaen,01-23 - Jaén,1,Andalucía,01 Andalucía
6,01-29,29,Málaga,Malaga,01-29 - Málaga,1,Andalucía,01 Andalucía
7,01-41,41,Sevilla,Sevilla,01-41 - Sevilla,1,Andalucía,01 Andalucía
8,02-22,22,Huesca,Huesca,02-22 - Huesca,2,Aragón,02 Aragón
9,02-44,44,Teruel,Teruel,02-44 - Teruel,2,Aragón,02 Aragón
10,02-50,50,Zaragoza,Zaragoza,02-50 - Zaragoza,2,Aragón,02 Aragón
11,03-33,33,Asturias,Asturias,03-33 - Asturias,3,Asturias,03 Asturias
12,04-07,7,Illes Balears,Illes Balears,04-07 - Illes Balears,4,Balears,04 Balears
13,05-35,35,Las Palmas,Las Palmas,05-35 - Las Palmas,5,Canarias,05 Canarias
14,05-38,38,Santa Cruz de Tenerife,Santa Cruz de Tenerife,05-38 - Santa Cruz de Tenerife,5,Canarias,05 Canarias
15,06-39,39,Cantabria,Cantabria,06-39 - Cantabria,6,Cantabria,06 Cantabria
16,07-05,5,Ávila,Avila,07-05 - Ávila,7,Castilla y León,07 Castilla y León
17,07-09,9,Burgos,Burgos,07-09 - Burgos,7,Castilla y León,07 Castilla y León
18,07-24,24,León,Leon,07-24 - León,7,Castilla y León,07 Castilla y León
19,07-34,34,Palencia,Palencia,07-34 - Palencia,7,Castilla y León,07 Castilla y León
20,07-37,37,Salamanca,Salamanca,07-37 - Salamanca,7,Castilla y León,07 Castilla y León
21,07-40,40,Segovia,Segovia,07-40 - Segovia,7,Castilla y León,07 Castilla y León
22,07-42,42,Soria,Soria,07-42 - Soria,7,Castilla y León,07 Castilla y León
23,07-47,47,Valladolid,Valladolid,07-47 - Valladolid,7,Castilla y León,07 Castilla y León
24,07-49,49,Zamora,Zamora,07-49 - Zamora,7,Castilla y León,07 Castilla y León
25,08-02,2,Albacete,Albacete,08-02 - Albacete,8,Castilla - La Mancha,08 Castilla - La Mancha
26,08-13,13,Ciudad Real,Ciudad Real,08-13 - Ciudad Real,8,Castilla - La Mancha,08 Castilla - La Mancha
27,08-16,16,Cuenca,Cuenca,08-16 - Cuenca,8,Castilla - La Mancha,08 Castilla - La Mancha
28,08-19,19,Guadalajara,Guadalajara,08-19 - Guadalajara,8,Castilla - La Mancha,08 Castilla - La Mancha
29,08-45,45,Toledo,Toledo,08-45 - Toledo,8,Castilla - La Mancha,08 Castilla - La Mancha
30,09-08,8,Barcelona,Barcelona,09-08 - Barcelona,9,Cataluña,09 Cataluña
31,09-17,17,Girona,Girona,09-17 - Girona,9,Cataluña,09 Cataluña
32,09-25,25,Lleida,Lleida,09-25 - Lleida,9,Cataluña,09 Cataluña
33,09-43,43,Tarragona,Tarragona,09-43 - Tarragona,9,Cataluña,09 Cataluña
34,10-03,3,Alicante / Alacant,Alicante / Alacant,10-03 - Alicante / Alacant,10,Valencia,10 Valencia
35,10-12,12,Castellón / Castelló,Castellon / Castello,10-12 - Castellón / Castelló,10,Valencia,10 Valencia
36,10-46,46,Valencia / València,Valencia / Valencia,10-46 - Valencia / València,10,Valencia,10 Valencia
37,11-06,6,Badajoz,Badajoz,11-06 - Badajoz,11,Extremadura,11 Extremadura
38,11-10,10,Cáceres,Caceres,11-10 - Cáceres,11,Extremadura,11 Extremadura
39,12-15,15,A Coruña,A Coruna,12-15 - A Coruña,12,Galicia,12 Galicia
40,12-27,27,Lugo,Lugo,12-27 - Lugo,12,Galicia,12 Galicia
41,12-32,32,Ourense,Ourense,12-32 - Ourense,12,Galicia,12 Galicia
42,12-36,36,Pontevedra,Pontevedra,12-36 - Pontevedra,12,Galicia,12 Galicia
43,13-28,28,Madrid,Madrid,13-28 - Madrid,13,Madrid,13 Madrid
44,14-30,30,Murcia,Murcia,14-30 - Murcia,14,Murcia,14 Murcia
45,15-31,31,Navarra,Navarra,15-31 - Navarra,15,Navarra,15 Navarra
46,16-01,1,Araba / Álava,Araba / Alava,16-01 - Araba / Álava,16,País Vasco,16 País Vasco
47,16-20,20,Gipuzkoa,Gipuzkoa,16-20 - Gipuzkoa,16,País Vasco,16 País Vasco
48,16-48,48,Bizkaia,Bizkaia,16-48 - Bizkaia,16,País Vasco,16 País Vasco
49,17-26,26,La Rioja,La Rioja,17-26 - La Rioja,17,La Rioja,17 La Rioja
50,18-51,51,Ceuta,Ceuta,18-51 - Ceuta,18,Ceuta,18 Ceuta
51,19-52,52,Melilla,Melilla,19-52 - Melilla,19,Melilla,19 Melilla

### 4. Exportar los datos a Excel

#### 4.1 Almacenamiento Tabla Dimensiones Provincias

In [7]:
#Exportar los resultados a Excel
df_provincias.to_excel("../Data/Silver/D_provincias_ine.xlsx", index=False)

#### 4.2 Almacenamiento Tabla Dimensiones CCAA

In [8]:
#Exportar los resultados a Excel
df_ccaa.to_excel("../Data/Silver/D_ccaa_ine.xlsx", index=False)

#### 4.3 Almacenamiento Tabla Dimensiones Geografía

In [9]:
#Exportar los resultados a Excel
df_geografia.to_excel("../Data/Gold/Dim/D_Geografia.xlsx", index=False)