### 1. Importar librerías y paquetes

In [1]:
#Importar librerías
import pandas as pd

### 2. Importar datos de origen

#### 2.1 Importar datos de Instalaciones

In [2]:
#Importar datos de Instalaciones (salida del notebook 02)
df_instalaciones = pd.read_excel(
    "../Data/Gold/Dim/MaestroInstalacionesGalicia.xlsx"
)

# Renombrar columnas
df_instalaciones = df_instalaciones.rename(columns={
    "propietario": "Propietario",
    "Cod-prv":"Cod_prv"
})

# Visualizar los resultados
df_instalaciones.head(5)

,Id_Instalacion,Clave_Registro,Nombre_Instalacion,Id_Propietario,Propietario,Id_ccaa,Cod_prv,Provincia,Municipio,Num_Registro,Cod_Grupo,Potencia_kw,Fase,Num_aerogeneradores,Fabricante,Modelo,Potencia_unitaria_kw,Tipo_Inscripcion,Fecha_Inscripcion
0,RE-000845-1,RE-000845,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Valadouro (O),RE-05-09,b.2.1,19500,1,26,NEG Micon,NM 750/44,750,DEFINITIVA,1999-11-26
1,RE-000846-1,RE-000846,P. E. ALABE-NORDES,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Valadouro (O),RE-05-10,b.2.1,20250,1,27,NEG Micon,NM44/750,750,DEFINITIVA,1999-11-26
2,RE-000847-1,RE-000847,P. E. ALABE-CUADRAMON,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Valadouro (O),RE-05-11,b.2.1,18750,1,25,NEG Micon,NM44/750,750,DEFINITIVA,1999-11-26
3,RE-000849-1,RE-000849,P. E. SERRA DO CANDO,PROP_047,"Olivento S.L., Sociedade Unipersoal",12,36,Pontevedra,Lama (A),RE-05-05,b.2.1,29230,1,44,Gamesa,G47 (43) / G52 (1),43×660; 1×850,DEFINITIVA,2000-11-02
4,RE-000850-1,RE-000850,P. E. MONTE SEIXO-CANDO,PROP_047,"Olivento S.L., Sociedade Unipersoal",12,36,Pontevedra,Lama (A),RE-99-57,b.2.1,34980,1,53,MADE,AE-46/I,660,DEFINITIVA,2000-11-02

#### 2.2 Importar datos de Ingresos

In [3]:
# Importar datos de 2025
df_ingresos_2025 = pd.read_excel("../Data/Raw/Dummy/Generacion_y_Ventas/Ingresos_parques_eolicos_Galicia_2025.xlsx")

# Visualizar los resultados
df_ingresos_2025.head(5)

,Año,Mes,Clave_Registro,Nombre_parque,energia_generada_gwh,energia_vendida_gwh,potencia_instalada_mw,precio_mercado_mwh_euro,ingresos_estimados_euro
0,2025,Enero,RE-000845-1,PARQUE EOLICO ALABE-SOAN,5.596,5.481,19.5,77.91,427026.50
1,2025,Febrero,RE-000845-1,PARQUE EOLICO ALABE-SOAN,4.788,4.690,19.5,58.65,275071.05
2,2025,Marzo,RE-000845-1,PARQUE EOLICO ALABE-SOAN,5.007,4.904,19.5,75.78,371630.67
3,2025,Abril,RE-000845-1,PARQUE EOLICO ALABE-SOAN,4.133,4.048,19.5,61.04,247087.12
4,2025,Mayo,RE-000845-1,PARQUE EOLICO ALABE-SOAN,3.681,3.606,19.5,68.45,246826.33

In [4]:
# Importar datos de 2024
df_ingresos_2024 = pd.read_excel("../Data/Raw/Dummy/Generacion_y_Ventas/Ingresos_parques_eolicos_Galicia_2024.xlsx")

# Visualizar los resultados
df_ingresos_2024.head(5)

,Año,Mes,Clave_Registro,Nombre_parque,energia_generada_gwh,energia_vendida_gwh,potencia_instalada_mw,precio_mercado_mwh_euro,ingresos_estimados_euro
0,2024,Enero,RE-000845-1,PARQUE EOLICO ALABE-SOAN,5.734,5.616,19.5,74.10,416145.60
1,2024,Febrero,RE-000845-1,PARQUE EOLICO ALABE-SOAN,4.053,3.937,19.5,40.00,157480.00
2,2024,Marzo,RE-000845-1,PARQUE EOLICO ALABE-SOAN,5.182,5.079,19.5,20.28,103002.12
3,2024,Abril,RE-000845-1,PARQUE EOLICO ALABE-SOAN,3.625,3.560,19.5,13.67,48665.20
4,2024,Mayo,RE-000845-1,PARQUE EOLICO ALABE-SOAN,3.802,3.699,19.5,30.40,112449.60

In [5]:
# Importar datos de 2023
df_ingresos_2023 = pd.read_excel("../Data/Raw/Dummy/Generacion_y_Ventas/Ingresos_parques_eolicos_Galicia_2023.xlsx")

# Eliminar columnas que no necesitamos
df_ingresos_2023 = df_ingresos_2023.drop(columns=["base_2024_aux"])

# Visualizar los resultados
df_ingresos_2023.head(5)

,Año,Mes,Clave_Registro,Nombre_parque,energia_generada_gwh,energia_vendida_gwh,potencia_instalada_mw,precio_mercado_mwh_euro,ingresos_estimados_euro
0,2023,Enero,RE-000845-1,PARQUE EOLICO ALABE-SOAN,5.734,5.27904,19.5,69.55,367157.2320
1,2023,Febrero,RE-000845-1,PARQUE EOLICO ALABE-SOAN,4.053,3.97637,19.5,133.47,530726.1039
2,2023,Marzo,RE-000845-1,PARQUE EOLICO ALABE-SOAN,5.182,4.92663,19.5,89.61,441475.3143
3,2023,Abril,RE-000845-1,PARQUE EOLICO ALABE-SOAN,3.625,3.70240,19.5,73.73,272977.9520
4,2023,Mayo,RE-000845-1,PARQUE EOLICO ALABE-SOAN,3.802,3.69900,19.5,74.21,274502.7900

### 3. Transformación de datos (tablas hechos)

#### 3.1 Tabla Hechos Ingresos Eólicas (general)

In [6]:
# Concatener dataframes
df_ingresos_eolicas = pd.concat(
    [df_ingresos_2025, df_ingresos_2024, df_ingresos_2023],
    ignore_index=True
)
#df_ingresos_eolicas.head(10)

# Renombrar columnas
df_ingresos_eolicas = df_ingresos_eolicas.rename(columns={
    "Año": "Ejercicio",
    "Clave_Registro":"Id_Instalacion",
    'energia_generada_gwh':'Energia_generada_gwh',
    'energia_vendida_gwh':'Energia_vendida_gwh', 
    'potencia_instalada_mw':'Potencia_instalada_mw',
    'precio_mercado_mwh_euro':'Precio_mercado_mwh_euro', 
    'ingresos_estimados_euro':'Ingresos_estimados_euro'
})

# Incluir Columna de Codigo_Mes
meses = {
    "Enero": 1,
    "Febrero": 2,
    "Marzo": 3,
    "Abril": 4,
    "Mayo": 5,
    "Junio": 6,
    "Julio": 7,
    "Agosto": 8,
    "Septiembre": 9,
    "Octubre": 10,
    "Noviembre": 11,
    "Diciembre": 12
}
df_ingresos_eolicas["Codigo_Mes"] = df_ingresos_eolicas["Mes"].map(meses)

# Incluir Columna de Codigo_Mes_str
df_ingresos_eolicas["Codigo_Mes_str"] = df_ingresos_eolicas["Mes"].map(meses).astype(str).str.zfill(2)

# Incluir Columna de Fecha
df_ingresos_eolicas["Fecha"] = pd.to_datetime(
    df_ingresos_eolicas["Ejercicio"].astype(str) + "-" + df_ingresos_eolicas["Codigo_Mes_str"] + "-01"
)

# Eliminar columnas que no se necesitan
df_ingresos_eolicas = df_ingresos_eolicas.drop(columns=["Codigo_Mes_str"])

# Alta columna "Id_Ingresos"
df_ingresos_eolicas['Id_Ingresos'] = df_ingresos_eolicas["Id_Instalacion"] + "_" +  df_ingresos_eolicas["Ejercicio"].astype(str) + "_" + df_ingresos_eolicas["Codigo_Mes"].astype(str)

# Reordenar columnas
df_ingresos_eolicas = df_ingresos_eolicas[['Ejercicio', 'Codigo_Mes', 'Mes', 'Fecha', 'Id_Ingresos', 'Id_Instalacion', 
                                           'Nombre_parque', 'Energia_generada_gwh','Energia_vendida_gwh',
                                           'Potencia_instalada_mw','Precio_mercado_mwh_euro', 'Ingresos_estimados_euro']]
# Visualizar los resultados
df_ingresos_eolicas

,Ejercicio,Codigo_Mes,Mes,Fecha,Id_Ingresos,Id_Instalacion,Nombre_parque,Energia_generada_gwh,Energia_vendida_gwh,Potencia_instalada_mw,Precio_mercado_mwh_euro,Ingresos_estimados_euro
0,2025,1,Enero,2025-01-01,RE-000845-1_2025_1,RE-000845-1,PARQUE EOLICO ALABE-SOAN,5.596,5.48100,19.5,77.91,427026.5000
1,2025,2,Febrero,2025-02-01,RE-000845-1_2025_2,RE-000845-1,PARQUE EOLICO ALABE-SOAN,4.788,4.69000,19.5,58.65,275071.0500
2,2025,3,Marzo,2025-03-01,RE-000845-1_2025_3,RE-000845-1,PARQUE EOLICO ALABE-SOAN,5.007,4.90400,19.5,75.78,371630.6700
3,2025,4,Abril,2025-04-01,RE-000845-1_2025_4,RE-000845-1,PARQUE EOLICO ALABE-SOAN,4.133,4.04800,19.5,61.04,247087.1200
4,2025,5,Mayo,2025-05-01,RE-000845-1_2025_5,RE-000845-1,PARQUE EOLICO ALABE-SOAN,3.681,3.60600,19.5,68.45,246826.3300
...,...,...,...,...,...,...,...,...,...,...,...,...
7555,2023,8,Agosto,2023-08-01,RE436-0604-1_2023_8,RE436-0604-1,P.E. LA CELAYA,4.037,3.83344,28.8,96.05,368201.9120
7556,2023,9,Septiembre,2023-09-01,RE436-0604-1_2023_9,RE436-0604-1,P.E. LA CELAYA,5.079,5.11368,28.8,103.34,528447.6912
7557,2023,10,Octubre,2023-10-01,RE436-0604-1_2023_10,RE436-0604-1,P.E. LA CELAYA,7.587,7.43000,28.8,90.14,669740.2000
7558,2023,11,Noviembre,2023-11-01,RE436-0604-1_2023_11,RE436-0604-1,P.E. LA CELAYA,8.673,8.08800,28.8,63.45,513183.6000
7559,2023,12,Diciembre,2023-12-01,RE436-0604-1_2023_12,RE436-0604-1,P.E. LA CELAYA,9.854,9.93641,28.8,72.17,717110.7097

In [7]:
#Join para incluir información adicional de aerogneradores, tecnología y otros
df_ingresos_eolicas_vf = df_ingresos_eolicas.merge(
    df_instalaciones[
        ["Id_Instalacion",'Id_Propietario', 'Propietario','Cod_prv', 'Provincia']
    ],
    how="left",
    left_on="Id_Instalacion",
    right_on="Id_Instalacion"
)

#Excluir registros con valores en blanco o nulos en el campo Id_Propietario
df_ingresos_eolicas_vf = df_ingresos_eolicas_vf[
    df_ingresos_eolicas_vf["Id_Propietario"].notna() &
    (df_ingresos_eolicas_vf["Id_Propietario"].str.strip() != "")
]

#Reordenar columnas
df_ingresos_eolicas_vf = df_ingresos_eolicas_vf[['Ejercicio', 'Codigo_Mes', 'Mes', 'Fecha', 'Id_Ingresos', 'Id_Instalacion', 
                                                 'Nombre_parque', 'Id_Propietario', 'Propietario','Cod_prv', 'Provincia',
                                                 'Energia_generada_gwh','Energia_vendida_gwh', 'Potencia_instalada_mw',
                                                 'Precio_mercado_mwh_euro', 'Ingresos_estimados_euro']]

#Visualizar los resultados
df_ingresos_eolicas_vf

,Ejercicio,Codigo_Mes,Mes,Fecha,Id_Ingresos,Id_Instalacion,Nombre_parque,Id_Propietario,Propietario,Cod_prv,Provincia,Energia_generada_gwh,Energia_vendida_gwh,Potencia_instalada_mw,Precio_mercado_mwh_euro,Ingresos_estimados_euro
0,2025,1,Enero,2025-01-01,RE-000845-1_2025_1,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,5.596,5.48100,19.5,77.91,427026.5000
1,2025,2,Febrero,2025-02-01,RE-000845-1_2025_2,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,4.788,4.69000,19.5,58.65,275071.0500
2,2025,3,Marzo,2025-03-01,RE-000845-1_2025_3,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,5.007,4.90400,19.5,75.78,371630.6700
3,2025,4,Abril,2025-04-01,RE-000845-1_2025_4,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,4.133,4.04800,19.5,61.04,247087.1200
4,2025,5,Mayo,2025-05-01,RE-000845-1_2025_5,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,3.681,3.60600,19.5,68.45,246826.3300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7555,2023,8,Agosto,2023-08-01,RE436-0604-1_2023_8,RE436-0604-1,P.E. LA CELAYA,PROP_004,"EDP Renovables España, S.L.",27.0,Lugo,4.037,3.83344,28.8,96.05,368201.9120
7556,2023,9,Septiembre,2023-09-01,RE436-0604-1_2023_9,RE436-0604-1,P.E. LA CELAYA,PROP_004,"EDP Renovables España, S.L.",27.0,Lugo,5.079,5.11368,28.8,103.34,528447.6912
7557,2023,10,Octubre,2023-10-01,RE436-0604-1_2023_10,RE436-0604-1,P.E. LA CELAYA,PROP_004,"EDP Renovables España, S.L.",27.0,Lugo,7.587,7.43000,28.8,90.14,669740.2000
7558,2023,11,Noviembre,2023-11-01,RE436-0604-1_2023_11,RE436-0604-1,P.E. LA CELAYA,PROP_004,"EDP Renovables España, S.L.",27.0,Lugo,8.673,8.08800,28.8,63.45,513183.6000
7559,2023,12,Diciembre,2023-12-01,RE436-0604-1_2023_12,RE436-0604-1,P.E. LA CELAYA,PROP_004,"EDP Renovables España, S.L.",27.0,Lugo,9.854,9.93641,28.8,72.17,717110.7097

#### 3.2 Tabla Hechos Generación

In [8]:
#DF para tabla de Generación
df_generacion = df_ingresos_eolicas_vf[['Ejercicio', 'Codigo_Mes', 'Mes', 'Fecha', 'Id_Ingresos', 'Id_Instalacion', 
                                        'Nombre_parque', 'Id_Propietario', 'Propietario','Cod_prv', 'Provincia',
                                        'Energia_generada_gwh']]

# Renombrar columnas
df_generacion = df_generacion.rename(columns={
    "Id_Ingresos": "Id_Generacion"
})

#Visualizar los resultados
df_generacion.head(10)

,Ejercicio,Codigo_Mes,Mes,Fecha,Id_Generacion,Id_Instalacion,Nombre_parque,Id_Propietario,Propietario,Cod_prv,Provincia,Energia_generada_gwh
0,2025,1,Enero,2025-01-01,RE-000845-1_2025_1,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,5.596
1,2025,2,Febrero,2025-02-01,RE-000845-1_2025_2,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,4.788
2,2025,3,Marzo,2025-03-01,RE-000845-1_2025_3,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,5.007
3,2025,4,Abril,2025-04-01,RE-000845-1_2025_4,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,4.133
4,2025,5,Mayo,2025-05-01,RE-000845-1_2025_5,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,3.681
5,2025,6,Junio,2025-06-01,RE-000845-1_2025_6,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,3.135
6,2025,7,Julio,2025-07-01,RE-000845-1_2025_7,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,2.945
7,2025,8,Agosto,2025-08-01,RE-000845-1_2025_8,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,3.092
8,2025,9,Septiembre,2025-09-01,RE-000845-1_2025_9,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,3.563
9,2025,10,Octubre,2025-10-01,RE-000845-1_2025_10,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,4.565

#### 3.3 Tabla Hechos Ventas

In [9]:
#DF para tabla de Ventas
df_ventas = df_ingresos_eolicas_vf[['Ejercicio', 'Codigo_Mes', 'Mes', 'Fecha', 'Id_Ingresos', 'Id_Instalacion', 
                                   'Nombre_parque', 'Id_Propietario', 'Propietario','Cod_prv', 'Provincia',
                                    'Energia_vendida_gwh', 'Potencia_instalada_mw','Precio_mercado_mwh_euro', 
                                    'Ingresos_estimados_euro']]
# Renombrar columnas
df_ventas = df_ventas.rename(columns={
    "Id_Ingresos": "Id_Ventas"
})

#Visualizar los resultados
df_ventas.head(5)

,Ejercicio,Codigo_Mes,Mes,Fecha,Id_Ventas,Id_Instalacion,Nombre_parque,Id_Propietario,Propietario,Cod_prv,Provincia,Energia_vendida_gwh,Potencia_instalada_mw,Precio_mercado_mwh_euro,Ingresos_estimados_euro
0,2025,1,Enero,2025-01-01,RE-000845-1_2025_1,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,5.481,19.5,77.91,427026.50
1,2025,2,Febrero,2025-02-01,RE-000845-1_2025_2,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,4.690,19.5,58.65,275071.05
2,2025,3,Marzo,2025-03-01,RE-000845-1_2025_3,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,4.904,19.5,75.78,371630.67
3,2025,4,Abril,2025-04-01,RE-000845-1_2025_4,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,4.048,19.5,61.04,247087.12
4,2025,5,Mayo,2025-05-01,RE-000845-1_2025_5,RE-000845-1,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",27.0,Lugo,3.606,19.5,68.45,246826.33

### 4. Exportar los datos a Excel

#### 4.1 Almacenamiento Tabla Generación

In [10]:
#Exportar los resultados a Excel
df_generacion.to_excel("../Data/Gold/Fact/Generacion_parques_eolicos_Galicia.xlsx", index=False)

#### 4.2 Almacenamiento Tabla Ingresos Eólicas (Silver)

In [11]:
#Exportar los resultados a Excel
df_ingresos_eolicas.to_excel("../Data/Silver/Ingresos_parques_eolicos_Galicia.xlsx", index=False)

#### 4.3 Almacenamiento Tabla Ventas

In [12]:
#Exportar los resultados a Excel
df_ventas.to_excel("../Data/Gold/Fact/Ventas_parques_eolicos_Galicia.xlsx", index=False)